const sidebars = {
  guideSidebar: [
    {
      type: "category",
      label: "Learn",
      items: [{ type: "autogenerated", dirName: "tutorials" }],
    },
    {
      type: "category",
      label: "Do",
      items: [{ type: "autogenerated", dirName: "how-to" }],
    },
    {
      type: "category",
      label: "Understand",
      items: [{ type: "autogenerated", dirName: "explanation" }],
    },
  ],
};

export default sidebars;
